# render.yaml
services:
  - type: web
    name: myProductAPI
    env: node
    region: oregon
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      - key: MONGO_URI
        value: YOUR_MONGODB_ATLAS_CONNECTION_STRING
